#!/bin/bash -p

make all || exit 1

server_type=$1
case "$server_type" in
    sync)  (sudo ./server-sync)& ;;
    async) (sudo ./server-async)& ;;
    *) echo "Usage $0 {async|sync}"; exit 1;;
esac
sleep 1
 ./client

